name: H2Integrate_config
system_summary: This reference hybrid plant contains a tidal power plant and an ocean alkalinity enhancement device
driver_config: driver_config.yaml
technology_config: tech_config.yaml
plant_config: plant_config.yaml
