H_MW = 1.008  # Molecular weight of Hydrogen in g/mol
N_MW = 14.007  # Molecular weight of Nitrogen in g/mol
# O2_MW = 31.998  # Molecular weight of Oxygen in g/mol
AR_MW = 39.948  # Molecular weight of Argon in g/mol
# FEO_MW = 71.8 # Molecular weight of Iron Oxide (FeO) in g/mol
# C_MW = 12.00 # Molecular weight of Carbon in g/mol
# CH4_MW = 16.00 # Molecular weight of Methane in g/mol
# CO2_MW = 44.00 # Molecular weight of Carbon Dioxide in g/mol
# CO_MW = 28.00 # Molecular weight of Carbon Monoxide in g/mol
# SIO2_MW = 60.00 # Molecular weight of Silicon Dioxide (Silica) in g/mol
# CAO_MW = 56.00 # Molecular weight of Calcium Oxide (Lime) in g/mol
# MGO_MW = 40.00 # Molecular weight of Magnesium Oxide in g/mol
LHV_CH4_MJ_PER_KG = 50.0  # Lower Heating Value of Natural Gas (Methane) in MJ/kg
HHV_H2_MJ_PER_KG = 141.86  # Higher Heating Value of Hydrogen in MJ/kg
# FE_MW = 55.845  # Molecular weight of Iron in g/mol
faraday = 96485.3321  # Faraday constant: Electric charge per mole of electrons (C/mol)

# if trying to match values exactly from decarbSTEEL use these constant values:
FEO_MW = 71.8  # Molecular weight of Iron Oxide (FeO) in g/mol
O2_MW = 32.00
C_MW = 12.00  # Molecular weight of Carbon in g/mol
CH4_MW = 16.00  # Molecular weight of Methane in g/mol
CO2_MW = 44.00  # Molecular weight of Carbon Dioxide in g/mol
CO_MW = 28.00  # Molecular weight of Carbon Monoxide in g/mol
SIO2_MW = 60.00  # Molecular weight of Silicon Dioxide (Silica) in g/mol
CAO_MW = 56.00  # Molecular weight of Calcium Oxide (Lime) in g/mol
MGO_MW = 40.00  # Molecular weight of Magnesium Oxide in g/mol
FE_MW = 55.80  # Molecular weight of Iron in g/mol
AL2O3_MW = 102.00  # Molecular weight of Aluminum Oxide (Al2O3) in g/mol
LHV_CH4_MJ_PER_KG = 50.0  # Lower Heating Value of Natural Gas (Methane) in MJ/kg
