description: Driver config for CSVGen design of experiments
name: driver_config
general:
  folder_output: outputs
  create_om_reports: false
driver:
  design_of_experiments:
    flag: true
    debug_print: false
    generator: csvgen
    filename: state_doe_ng_prices.csv
    run_parallel: false
design_variables:
  site:
    latitude:
      flag: true
      units: deg
      lower: -90.0
      upper: 90.0
    longitude:
      flag: true
      units: deg
      lower: -180.0
      upper: 180.0
  ng_feedstock:
    price:
      flag: true
      units: USD/MMBtu
      lower: 0.0
      upper: 25.0
objective:
  name: finance_subgroup_hydrogen.LCOH
recorder:
  file: cases.sql
  overwrite_recorder: true
  flag: true
  includes: ['*']
  excludes: ['*wind_resource*']
