name: technology_config
description: this is a plant
technologies:
  ng_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: natural_gas
        commodity_rate_units: MMBtu/h
      performance_parameters:
        rated_capacity: 750.  # MMBtu - TODO: update
      cost_parameters:
        cost_year: 2022
        price: 4.2  # USD/MMBtu
        annual_cost: 0.
        start_up_cost: 0.
  grid_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: MW
      performance_parameters:
        rated_capacity: 30.  # TODO: udpate
      cost_parameters:
        commodity_amount_units: MW*h
        cost_year: 2022
        price: 58.02  # USD/MWh, UPDATE
        annual_cost: 0.
        start_up_cost: 0.
  smr:
    performance_model:
      model: null
    cost_model:
      model: null
    model_inputs:
      shared_parameters: null
      performance_parameters: null
      cost_parameters: null
