name: Testing
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: 0 0 * * MON
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.11'
          - '3.13'
        optional:
          - true
        include:
          - python-version: '3.11'
            optional: false
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate: true
          activate-environment: h2integrate
      - name: Install base dependencies
        shell: bash -el {0}
        env:
          SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: true
        run: |
          conda install -y -c conda-forge glpk coin-or-cbc>=2.10.12
          python -m pip install --upgrade pip
          pip install ".[develop]"
      - if: ${{ matrix.optional }}
        name: Install optional dependencies
        shell: bash -el {0}
        run: |
          conda install -y -c conda-forge wisdem
          pip install ".[extras]"
      - name: Create env file
        run: |
          touch .env
      - name: Run unit tests
        shell: bash -el {0}
        run: pytest . -m unit --cov=h2integrate --cov-report=lcov:./unit-coverage.lcov
      - name: Run regression tests
        shell: bash -el {0}
        run: pytest . -m regression --cov=h2integrate --cov-report=lcov:./regression-coverage.lcov
      - name: Run integration tests
        shell: bash -el {0}
        run: pytest . -m integration --cov=h2integrate --cov-report=lcov:./integration-coverage.lcov
      - name: Upload test coverage
        uses: coverallsapp/github-action@v2
        if: contains( matrix.os, 'ubuntu') && contains( matrix.python-version, '3.13')
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          files: ./unit-coverage.lcov, ./regression-coverage.lcov, ./integration-coverage.lcov
          flag-name: unit,regression,integration
          fail-on-error: false
